// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOAPrPyTGVMqhk7EI2pDHJUnyLa9x1DI',
    appId: '1:1050913441068:web:63bb9592364edcf8071889',
    messagingSenderId: '1050913441068',
    projectId: 'ketchup-c2079',
    authDomain: 'ketchup-c2079.firebaseapp.com',
    storageBucket: 'ketchup-c2079.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1pXFPjb2yaWmYUXQDugwt278uNjfzQ4',
    appId: '1:1050913441068:android:68322814a47b611b071889',
    messagingSenderId: '1050913441068',
    projectId: 'ketchup-c2079',
    storageBucket: 'ketchup-c2079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotwDlKAG1xwk3BfaI4m5SzvShyQR8GUQ',
    appId: '1:1050913441068:ios:77a8473db634683e071889',
    messagingSenderId: '1050913441068',
    projectId: 'ketchup-c2079',
    storageBucket: 'ketchup-c2079.firebasestorage.app',
    iosBundleId: 'com.example.ketchup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotwDlKAG1xwk3BfaI4m5SzvShyQR8GUQ',
    appId: '1:1050913441068:ios:77a8473db634683e071889',
    messagingSenderId: '1050913441068',
    projectId: 'ketchup-c2079',
    storageBucket: 'ketchup-c2079.firebasestorage.app',
    iosBundleId: 'com.example.ketchup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOAPrPyTGVMqhk7EI2pDHJUnyLa9x1DI',
    appId: '1:1050913441068:web:851017450cff423d071889',
    messagingSenderId: '1050913441068',
    projectId: 'ketchup-c2079',
    authDomain: 'ketchup-c2079.firebaseapp.com',
    storageBucket: 'ketchup-c2079.firebasestorage.app',
  );
}
